language: generic
# Only build if release + tag + latest master commit
script: bash bin/check_to_build.sh || travis_terminate 0
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: README.md
  skip_cleanup: true
  on:
    tags: true
