language: generic
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: README.md
  skip_cleanup: true
  on:
    tags: true
dd:
  secure: g583c8M+JDFnBcBQ3CH2hzJWIXFgHFolyZU6yp1UtsPxlDnKxWk9mHUDo8Pv8sjVcp4gsXtFFSBkVo0RGRSOly7/CnAwXyVpEIOwRPfLFzEitMr+p0AxlywAd5M9QTyiUF1QazokkZlCGZOmKbBXsUl6poALELBnxKA5krydTf/Hv4VbiXGwrie7Dr2hY1WY/Pi9/5lBbAx8gqCOlIUPa7bFvGgvi0J5OlS+G2jk+kgJfAXhzAfSojO0MYip8CjHNBuIwE9yS2FruBAkFcBiz+uqcGbcNOwr36d7czTRVRDCAVcGZc2zzgo3BssGLBM8W0UTFwwuCl71fB+pBGftBRzdRjr+0nxejo/ZW8c4CQymE1fxSG9pxq3jG2TNPDB2llgBzZEQKr71UlEGaLCe3QShzz+4KjRXPHCSGQbbojlVsQtF5JLNQirV3O7bpbbvKOBC7Vb5RLbq6aLHQG+VBdQeIzExDnrnIhFUzf/f4nZtdxV2Y0AL/ixJrhP/u2e5CXtjghFmA8o3z2hrBe34gbemrsCmt7zAn47pGuloK1gowkg2SBCyg6oM2PDMgAX7xX4XH47L9TaCd11PmxFpZIcEA4r3PiurBM90GJsmD67I1A6TwqJYp+rqKS9Wya1AVzrBVPJ6wtdXQGiG4MrWQBKwbhNKy/WBTNeZuCrWVEU=
